env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:solid/typescript
overrides: [ ]
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - simple-import-sort
  - unused-imports
  - '@typescript-eslint'
  - solid
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  comma-dangle:
    - error
    - always-multiline
  function-paren-newline:
    - error
    - consistent
  function-call-argument-newline:
    - error
    - consistent
  max-len:
    - error
    - code: 120
      ignoreComments: true
      ignoreTrailingComments: true
      ignoreUrls: true
      ignoreTemplateLiterals: true
      ignorePattern: '^\s*d="' # ignore svg path declarations
  '@typescript-eslint/no-unused-vars':
    - error
    - vars: all
      varsIgnorePattern: '^_'
      args: after-used
      argsIgnorePattern: '^_'
  simple-import-sort/imports: warn
  simple-import-sort/exports: warn
  unused-imports/no-unused-imports: error
